### ISSUE TITLE
Is there a way to limit movement/add collisions?

### ISSUE THREAD

**Issue by PLyczkowski** [Bauxitedev/godot-jigglebones#2]
For example, if I have a pendant for a character, can I somehow prevent it from going into the character?

**Comment by Bauxitedev** [comment]
No, it does not support collision at the moment. You can instead use the new [PhysicalBone](https://godotengine.org/article/godot-ragdoll-system) which does support collision.

**Comment by PLyczkowski** [comment]
Ooh, that seems to be what I'm looking for, thanks so much!
