### ISSUE TITLE
scene fails to load! help

### ISSUE THREAD

**Issue by aztecsensei** [Bauxitedev/godot-jigglebones#3]
hello! ive this problem where my scene cant load, it looks like its jigglebones issue.
here its pic:
![2018-12-28_202737](https://user-images.githubusercontent.com/33324484/50539692-eee4c900-0b49-11e9-8617-c0ce54cf16a9.jpg)

![2018-12-29_091654](https://user-images.githubusercontent.com/33324484/50539726-93670b00-0b4a-11e9-84f2-9d05122b1b10.jpg)

if you need to take a look at the project i can share it by twitter message.

thx

**Comment by Bauxitedev** [comment]
From the looks of it, you're using the nightly build of Godot. Do you know which build is it exactly? From which date is it? It might have changed something that breaks the addon.

**Comment by aztecsensei** [comment]
hey! thanks for answer, for a moment i thought you abandoned the addon! : (
sorry i forgot to add the build number :  10e9221.
i think u gonna have to take a look the scene but it looks like github files are public ,can i send it by twitter?
._.

**Comment by Bauxitedev** [comment]
Someone just mentioned there is a change in Godot 3.1 that breaks the addon (something to do with enums), I will check if I can fix it without breaking compatibility with Godot 3.0. Currently a bit busy with other stuff, but you can expect a fix somewhere next week.

**Comment by Bauxitedev** [comment]
Fixed. I'll update the asset in the asset store soon.
